-- 코드를 작성해주세요

SELECT I.ITEM_ID ITEM_ID, I.ITEM_NAME ITEM_NAME, I.RARITY RARITY
FROM  ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC