-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE O 
WHERE O.SALES_DATE LIKE "2022-03-%" 
union all
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d")  AS SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE F 
WHERE F.SALES_DATE LIKE "2022-03-%"
ORDER BY SALES_DATE , PRODUCT_ID , USER_ID