-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y") YEAR,DATE_FORMAT(SALES_DATE,"%m") MONTH,I.GENDER GENDER, COUNT(DISTINCT(O.USER_ID))
FROM USER_INFO I JOIN ONLINE_SALE O ON I.USER_ID=O.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER 
ORDER BY YEAR,MONTH,GENDER
