-- 코드를 입력하세요
SELECT DATE_FORMAT(O.SALES_DATE,"%Y") YEAR,
DATE_FORMAT(O.SALES_DATE,"%m") MONTH,
COUNT(DISTINCT I.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT I.USER_ID)/(
    SELECT COUNT(DISTINCT USER_ID)
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"

),1)
FROM USER_INFO I JOIN ONLINE_SALE O ON I.USER_ID=O.USER_ID
WHERE DATE_FORMAT(JOINED,"%Y")=2021
GROUP BY YEAR,MONTH