# -- 코드를 입력하세요
SELECT O.PRODUCT_ID AS PRODUCT_ID , P.PRODUCT_NAME, O.TOTAL_SALES*P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P 
JOIN(
SELECT PRODUCT_ID,SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID
) O ON P.PRODUCT_ID=O.PRODUCT_ID
ORDER BY O.TOTAL_SALES*P.PRICE DESC, O.PRODUCT_ID ASC

# SELECT PRODUCT_ID,SUM(AMOUNT) AS TOTAL_SALES
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE LIKE "2022-05%"
# GROUP BY PRODUCT_ID