-- 코드를 입력하세요
# SELECT
# from member_profile as m, rest_review as r
# where 

SELECT M.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d")
FROM MEMBER_PROFILE M JOIN REST_REVIEW R 
ON M.MEMBER_ID=R.MEMBER_ID
WHERE R.MEMBER_ID=(
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT	 ASC
