-- 코드를 입력하세요
# SELECT B.CATEGORY, COUNT(SALES) 판매량
# FROM BOOK B JOIN BOOK_SALES BS ON B.BOOK_ID=BS.BOOK_ID
# WHERE BS.SALES_DATE LIKE '2022-01%'
# GROUP BY B.CATEGORY
# ORDER BY B.CATEGORY

SELECT B.CATEGORY,SUM(SALES) 판매량
FROM BOOK B JOIN BOOK_SALES BS ON B.BOOK_ID=BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY